spring:
  datasource:
    url: jdbc:h2:~/db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect

application:
  proxy:
    host: 192.168.15.10
    port: 8080
    noProxy: localhost|127.0.0.1
